<script lang="ts">
    import { onMount } from 'svelte';
    import { coefficients, isLoading, error, isAdjustingPrices, isTrainingModel, coefficientHelpers } from '$lib/stores/controls';
    import type { CoefficientData } from '$lib/stores/controls';

    let coefficientData: CoefficientData | null = null;
    let showTooltip: string | null = null;

    // Subscribe to the store
    coefficients.subscribe(value => {
        coefficientData = value;
    });

    onMount(async () => {
        await coefficientHelpers.fetchCoefficients();
    });

    // Format date to readable string
    function formatDate(dateString: string): string {
        return new Date(dateString).toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        });
    }

    // Format number to handle very small values
    function formatNumber(num: number): string {
        if (Math.abs(num) < 0.0001 && num !== 0) {
            return num.toExponential(4);
        }
        return num.toFixed(4);
    }

    // Get coefficient impact color
    function getCoefficientColor(value: number): string {
        if (value > 0) return 'text-green-600';
        if (value < 0) return 'text-red-600';
        return 'text-gray-600';
    }

    // Get coefficient impact icon
    function getCoefficientIcon(value: number): string {
        if (value > 0) return '↗️';
        if (value < 0) return '↘️';
        return '➡️';
    }

    // Handle price adjustment
    async function handleAdjustPrices() {
        const result = await coefficientHelpers.adjustPrices();
        if (result.success) {
            // Optionally show success message or refresh data
        }
    }

    // Handle model training
    async function handleTrainModel() {
        const result = await coefficientHelpers.trainModel();
        if (result.success) {
            // Coefficients will be automatically refreshed after training
        }
    }

    // Coefficient explanations
    const coefficientExplanations = {
        days_since_last_sale: {
            title: "Days Since Last Sale",
            description: "How the number of days since the last sale affects pricing. Higher values typically indicate slower-moving inventory.",
            impact: "Positive: Increase price for stale inventory | Negative: Decrease price to move stale inventory"
        },
        sales_velocity: {
            title: "Sales Velocity",
            description: "The rate at which products sell over time. Fast-selling items may command higher prices.",
            impact: "Positive: Higher velocity = Higher price | Negative: Higher velocity = Lower price (volume discount)"
        },
        total_sales_count: {
            title: "Total Sales Count",
            description: "The cumulative number of units sold. Popular products may have pricing advantages.",
            impact: "Positive: More sales = Higher price (popularity premium) | Negative: More sales = Lower price (volume discount)"
        },
        total_sales_value: {
            title: "Total Sales Value",
            description: "The cumulative revenue generated by the product. High-value products may sustain premium pricing.",
            impact: "Positive: Higher value = Higher price | Negative: Higher value = Lower price (accessibility strategy)"
        },
        category_percentile: {
            title: "Category Percentile",
            description: "Where the product ranks within its category. Top performers may command premium pricing.",
            impact: "Positive: Higher rank = Higher price | Negative: Higher rank = Lower price (competitive strategy)"
        },
        review_score: {
            title: "Review Score",
            description: "Average customer rating. Better reviews typically support higher pricing.",
            impact: "Positive: Better reviews = Higher price | Negative: Better reviews = Lower price (value strategy)"
        },
        wishlist_to_sales_ratio: {
            title: "Wishlist to Sales Ratio",
            description: "Ratio of wishlist additions to actual sales. High ratios may indicate price sensitivity.",
            impact: "Positive: Higher ratio = Higher price (demand indication) | Negative: Higher ratio = Lower price (conversion focus)"
        },
        days_since_restock: {
            title: "Days Since Restock",
            description: "Time elapsed since inventory replenishment. Affects scarcity-based pricing decisions.",
            impact: "Positive: Longer time = Higher price (scarcity) | Negative: Longer time = Lower price (clearance)"
        }
    };
</script>

<div class="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
    <div class="container mx-auto p-6">
        <!-- Header Section -->
        <div class="bg-white shadow-xl rounded-2xl mb-8 overflow-hidden">
            <div class="bg-gradient-to-r from-blue-600 to-indigo-700 p-6">
                <div class="flex justify-between items-center">
                    <div>
                        <h1 class="text-3xl font-bold text-white mb-2">Dynamic Pricing Model</h1>
                        <p class="text-blue-100">AI-driven coefficient analysis and price optimization</p>
                    </div>
                    <div class="text-right text-blue-100">
                        <div class="text-2xl font-bold">📊</div>
                        <div class="text-sm">Admin Dashboard</div>
                    </div>
                </div>
            </div>
            
            <!-- Action Buttons -->
            <div class="p-6 bg-gray-50 border-b">
                <div class="flex flex-wrap gap-4 justify-center">
                    <button
                        on:click={handleAdjustPrices}
                        disabled={$isAdjustingPrices}
                        class="flex items-center px-6 py-3 bg-gradient-to-r from-blue-600 to-blue-700 text-white rounded-xl hover:from-blue-700 hover:to-blue-800 disabled:from-blue-300 disabled:to-blue-400 disabled:cursor-not-allowed transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105"
                    >
                        {#if $isAdjustingPrices}
                            <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                            </svg>
                            Adjusting Prices...
                        {:else}
                            <span class="mr-2">💰</span>
                            Adjust All Prices
                        {/if}
                    </button>
                    
                    <button
                        on:click={handleTrainModel}
                        disabled={$isTrainingModel}
                        class="flex items-center px-6 py-3 bg-gradient-to-r from-green-600 to-emerald-700 text-white rounded-xl hover:from-green-700 hover:to-emerald-800 disabled:from-green-300 disabled:to-emerald-400 disabled:cursor-not-allowed transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105"
                    >
                        {#if $isTrainingModel}
                            <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                            </svg>
                            Training Model...
                        {:else}
                            <span class="mr-2">🧠</span>
                            Train Model
                        {/if}
                    </button>
                </div>
            </div>
        </div>

        {#if $isLoading}
            <div class="flex justify-center items-center h-64">
                <div class="text-center">
                    <div class="animate-spin rounded-full h-16 w-16 border-4 border-blue-200 border-t-blue-600 mx-auto mb-4"></div>
                    <p class="text-gray-600 text-lg">Loading coefficient data...</p>
                </div>
            </div>
        {:else if $error}
            <div class="bg-red-50 border-l-4 border-red-500 p-6 rounded-lg shadow-lg">
                <div class="flex items-center">
                    <span class="text-2xl mr-3">⚠️</span>
                    <div>
                        <h3 class="text-red-800 font-bold text-lg">Error Loading Data</h3>
                        <p class="text-red-700">{$error}</p>
                    </div>
                </div>
            </div>
        {:else if coefficientData}
            <!-- Model Overview Cards -->
            <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                <div class="bg-white rounded-xl shadow-lg p-6 border-l-4 border-blue-500">
                    <div class="flex items-center justify-between">
                        <div>
                            <h3 class="text-gray-500 text-sm font-medium">Model Version</h3>
                            <p class="text-2xl font-bold text-gray-900">{coefficientData.model_version}</p>
                        </div>
                        <div class="text-3xl">🔢</div>
                    </div>
                </div>
                
                <div class="bg-white rounded-xl shadow-lg p-6 border-l-4 border-green-500">
                    <div class="flex items-center justify-between">
                        <div>
                            <h3 class="text-gray-500 text-sm font-medium">Sample Size</h3>
                            <p class="text-2xl font-bold text-gray-900">{coefficientData.sample_size.toLocaleString()}</p>
                        </div>
                        <div class="text-3xl">📈</div>
                    </div>
                </div>
                
                <div class="bg-white rounded-xl shadow-lg p-6 border-l-4 border-purple-500">
                    <div class="flex items-center justify-between">
                        <div>
                            <h3 class="text-gray-500 text-sm font-medium">Model Accuracy (R²)</h3>
                            <p class="text-2xl font-bold text-gray-900">{(coefficientData.r_squared * 100).toFixed(1)}%</p>
                        </div>
                        <div class="text-3xl">🎯</div>
                    </div>
                </div>
            </div>

            <!-- Performance Metrics -->
            <div class="bg-white rounded-xl shadow-lg mb-8 overflow-hidden">
                <div class="bg-gradient-to-r from-purple-600 to-pink-600 p-4">
                    <h2 class="text-xl font-bold text-white flex items-center">
                        <span class="mr-2">📊</span>
                        Model Performance Metrics
                    </h2>
                </div>
                <div class="p-6">
                    <div class="grid grid-cols-2 md:grid-cols-4 gap-6">
                        <div class="text-center">
                            <div class="text-3xl font-bold text-purple-600">{formatNumber(coefficientData.r_squared)}</div>
                            <div class="text-sm text-gray-500 mt-1">R-Squared</div>
                            <div class="text-xs text-gray-400">Variance Explained</div>
                        </div>
                        <div class="text-center">
                            <div class="text-3xl font-bold text-pink-600">{formatNumber(coefficientData.mse)}</div>
                            <div class="text-sm text-gray-500 mt-1">MSE</div>
                            <div class="text-xs text-gray-400">Mean Squared Error</div>
                        </div>
                        <div class="text-center">
                            <div class="text-3xl font-bold text-indigo-600">{formatNumber(coefficientData.rmse)}</div>
                            <div class="text-sm text-gray-500 mt-1">RMSE</div>
                            <div class="text-xs text-gray-400">Root Mean Squared Error</div>
                        </div>
                        <div class="text-center">
                            <div class="text-3xl font-bold text-blue-600">{formatNumber(coefficientData.mae)}</div>
                            <div class="text-sm text-gray-500 mt-1">MAE</div>
                            <div class="text-xs text-gray-400">Mean Absolute Error</div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Coefficients Grid -->
            <div class="bg-white rounded-xl shadow-lg overflow-hidden">
                <div class="bg-gradient-to-r from-emerald-600 to-teal-600 p-4">
                    <h2 class="text-xl font-bold text-white flex items-center">
                        <span class="mr-2">⚙️</span>
                        Feature Coefficients & Impact Analysis
                    </h2>
                    <p class="text-emerald-100 text-sm mt-1">How each factor influences pricing decisions</p>
                </div>
                
                <div class="p-6">
                    <div class="grid gap-6">
                        {#each Object.entries(coefficientExplanations) as [key, explanation]}
                            {@const coeffValue = (coefficientData as any)[`${key}_coef`]}
                            <div class="bg-gray-50 rounded-lg p-4 hover:bg-gray-100 transition-colors duration-200 border border-gray-200">
                                <div class="flex items-start justify-between">
                                    <div class="flex-1">
                                        <div class="flex items-center mb-2">
                                            <h3 class="text-lg font-semibold text-gray-800 mr-3">{explanation.title}</h3>
                                            <span class="text-2xl">{getCoefficientIcon(coeffValue)}</span>
                                            <span class="ml-2 px-3 py-1 rounded-full text-sm font-medium {getCoefficientColor(coeffValue)} bg-white border">
                                                {formatNumber(coeffValue)}
                                            </span>
                                        </div>
                                        <p class="text-gray-600 mb-3 text-sm leading-relaxed">{explanation.description}</p>
                                        <div class="bg-white p-3 rounded border-l-4 {coeffValue > 0 ? 'border-green-400' : coeffValue < 0 ? 'border-red-400' : 'border-gray-400'}">
                                            <p class="text-xs text-gray-500 font-medium mb-1">PRICING IMPACT:</p>
                                            <p class="text-sm text-gray-700">{explanation.impact}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {/each}
                    </div>
                </div>
            </div>

            <!-- Footer Info -->
            <div class="mt-8 bg-white rounded-xl shadow-lg p-6">
                <div class="flex flex-col md:flex-row justify-between items-center text-sm text-gray-500">
                    <div class="mb-2 md:mb-0">
                        <strong>Training Date:</strong> {formatDate(coefficientData.training_date)}
                    </div>
                    <div>
                        <strong>Last Updated:</strong> {formatDate(coefficientData.updated_at)}
                    </div>
                </div>
            </div>
        {:else}
            <div class="text-center py-12">
                <div class="text-6xl mb-4">📊</div>
                <h3 class="text-xl text-gray-600 mb-2">No coefficient data available</h3>
                <p class="text-gray-500">Train the model to generate coefficient data</p>
            </div>
        {/if}
    </div>
</div>

<style>
    /* Custom scrollbar for better aesthetics */
    :global(::-webkit-scrollbar) {
        width: 8px;
    }
    
    :global(::-webkit-scrollbar-track) {
        background: #f1f5f9;
        border-radius: 4px;
    }
    
    :global(::-webkit-scrollbar-thumb) {
        background: #cbd5e1;
        border-radius: 4px;
    }
    
    :global(::-webkit-scrollbar-thumb:hover) {
        background: #94a3b8;
    }
</style>